version: '3,8'
services: 
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smarthub
    networks:
      - mussarri
  
networks:
  mussarri: